defaults: &defaults

development:
  <<: *defaults
  AWS_ACCESS_KEY: ""
  AWS_SECRET_KEY: ""
  AWS_BUCKET: ""


test:
  <<: *defaults

production:
  <<: *defaults

staging:
  <<: *defaults
  AWS_ACCESS_KEY: ""
  AWS_SECRET_KEY: ""
  AWS_BUCKET: ""
