defaults: &defaults

development:
  <<: *defaults
  AWS_ACCESS_KEY: "AKIAJH6OPC5MWSQX6VLQ"
  AWS_SECRET_KEY: "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"
  AWS_BUCKET: "sealpropertiesus"


test:
  <<: *defaults

production:
  <<: *defaults
  AWS_ACCESS_KEY: "AKIAJH6OPC5MWSQX6VLQ"
  AWS_SECRET_KEY: "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"
  AWS_BUCKET: "sealpropertiesus"
